# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [8]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [9]:
#todo: 

import numpy as np

# Crea un array con los números del 0 al 9
array = np.arange(10)

# Imprime el array
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [10]:
#todo:
import numpy as np

# Crea un array de 5 ceros
array = np.zeros(5)

# Cambia el tercer elemento (índice 2) a 5
array[2] = 5

print(array)

[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [16]:
#todo: 
import numpy as np

# Genera una matriz 3x3 de números aleatorios entre 0 y 1
matriz = np.random.rand (3,3)

print(matriz)


[[0.65751111 0.28348399 0.09171614]
 [0.36675098 0.56632405 0.79608838]
 [0.71795535 0.126721   0.34165827]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:
import numpy as np

# Array inicial
arr = np.array([10, 20, 30, 40, 50])

# Suma 5 a cada elemento
arr_sum = arr + 5

# 2. Genera un número aleatorio
random_num = np.random.random() * 10  # Esto genera un número aleatorio entre 0 y 10

# Multiplica todo por el número aleatorio
arr_mul = arr_sum * random_num

# Imprimir los resultados
print(f"Array original: {arr}")
print(f"Array después de sumar 5: {arr_sum}")
print(f"Número aleatorio generado: {random_num}")
print(f"Array después de multiplicar por el número aleatorio: {arr_mul}")


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
import numpy as np

# Crea una matriz identidad de tamaño 4x4
matriz_identidad = np.eye(4)

print(matriz_identidad)


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares y luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 
import numpy as np

# Crea un array con números pares de 0 a 20
array_pares = np.arange(0, 21, 2)

# Operaciones básicas (Ejemplos)

# Suma
suma = array_pares + 5

# Resta
resta = array_pares - 3

# Multiplicación
multiplicacion = array_pares * 2

# División
division = array_pares / 2

# Imprime los resultados
print(f"Array original (números pares): {array_pares}")
print(f"Suma de 5 a cada elemento: {suma}")
print(f"Resta de 3 a cada elemento: {resta}")
print(f"Multiplicación por 2 a cada elemento: {multiplicacion}")
print(f"División por 2 a cada elemento: {division}")
